.PHONY: go powershell
all: go powershell

go:
	curl -LO https://raw.githubusercontent.com/fatih/vim-go/master/syntax/gohtmltmpl.vim 
	curl -LO https://raw.githubusercontent.com/fatih/vim-go/master/syntax/gomod.vim
	curl -LO https://raw.githubusercontent.com/fatih/vim-go/master/syntax/gotexttmpl.vim

powershell:
	curl -LO https://raw.githubusercontent.com/vim/vim/master/runtime/syntax/ps1.vim
